name: build
jobs:
  clusterId: 4
  build:
    runs-on: steden88/cicd:3.0-npm # 工作流运行的环境
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn

    steps:
      - name: 安装go
        uses: setup-go@v1
        with:

      - name: 拉取应用Git
        uses: checkout@v1 # 在fops配置了依赖时，将自动拉取所有依赖Git

      - name: 编译
        run:
          - unset HTTPS_PROXY
          - unset HTTP_PROXY
          - rm -rf ./go.work
          - go work init ./
          - go work edit -replace github.com/farseer-go/fs=../farseer-go/fs
          - go work edit -replace github.com/farseer-go/docker=../farseer-go/docker
          - go work edit -replace github.com/farseer-go/mapper=../farseer-go/mapper
          - go work edit -replace github.com/farseer-go/queue=../farseer-go/queue
          - go work edit -replace github.com/farseer-go/utils=../farseer-go/utils
          - go work edit -replace github.com/farseer-go/collections=../farseer-go/collections
          - go work edit -replace github.com/farseer-go/webapi=../farseer-go/webapi
          - go work edit -replace github.com/farseer-go/tasks=../farseer-go/tasks
          - go mod download
          - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./fops-agent -ldflags="-w -s" .

      - name: 打包镜像
        uses: dockerBuild@v1

      - name: 上传镜像
        uses: dockerPush@v1

      - name: 更新镜像
        uses: dockerswarmUpdateVer@v1
        with:
          remoteClusterId: 1