#!/bin/bash

# 定义参数
APP_NAME="fops-agent"
VERSION="v0.1.0"
INSTALL_DIR="/usr/local/bin"
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"

# ====== 参数解析 ======
# 需要设置的环境变量（格式: VAR_NAME="value"）
ENV_VARS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      if [[ -n "$2" && "$2" != -* ]]; then
        # 验证变量格式是否为 KEY=VALUE
        if [[ "$2" =~ ^[a-zA-Z_][a-zA-Z0-9_]*=.* ]]; then
          ENV_VARS+=("$2")
          shift 2
        else
          echo "错误: --env 参数格式应为 KEY=VALUE，实际输入: $2" >&2
          exit 1
        fi
      else
        echo "错误: --env 需要参数值" >&2
        exit 1
      fi
      ;;
    *)
      echo "未知参数: $1" >&2
      exit 1
      ;;
  esac
done

# 检查 root 权限
if [ "$(id -u)" != "0" ]; then
   echo "请使用 sudo 运行此脚本" >&2
   exit 1
fi

# 下载二进制文件
echo "正在下载 ${APP_NAME}.$(uname -s).$(uname -m):${VERSION}..."
DOWNLOAD_URL="https://github.com/farseers/FOPS-Agent/releases/download/${VERSION}/${APP_NAME}.$(uname -s).$(uname -m)"
if ! wget -O "${INSTALL_DIR}/${APP_NAME}" "${DOWNLOAD_URL}"; then
   echo "下载失败，请检查版本号和网络连接" >&2
   exit 1
fi

# 设置可执行权限
chmod +x "${INSTALL_DIR}/${APP_NAME}"

# 设置永久环境变量
echo "配置环境变量..."
ENV_FILE="/etc/profile.d/${APP_NAME}.sh"
cat > "${ENV_FILE}" <<EOF
#!/bin/sh
# Auto-generated by ${APP_NAME} installer
${ENV_VARS[@]}
EOF

# 创建 systemd 服务文件
echo "创建服务文件..."
cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=${APP_NAME} Service
After=network.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/${APP_NAME}
Restart=always
RestartSec=5
User=root
WorkingDirectory=${INSTALL_DIR}
$(for var in "${ENV_VARS[@]}"; do echo "Environment=${var}"; done)

[Install]
WantedBy=multi-user.target
EOF

# 重载 systemd
systemctl daemon-reload

# 启用并启动服务
systemctl enable "${APP_NAME}"
systemctl start "${APP_NAME}"

# 立即生效环境变量（当前会话）
source "${ENV_FILE}"

echo "安装完成！"
echo "管理命令："
echo "  sudo systemctl status ${APP_NAME}"
echo "  sudo systemctl restart ${APP_NAME}"